name = "cf-webssh"
main = "dist/index.js"
# 將日期更新至 2025-01-01，以原生啟用完整版的 node:net/dns 相容層
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "WEBSSH_KV"
id = "KV_NAMESPACE_ID_PLACEHOLDER"
